import { db } from "../db/index";
import { schemes } from "../db/schemas/scheme";
import * as dotenv from "dotenv";

dotenv.config({ path: ".env" });

const healthcareSchemes = [
    {
        title: "Ayushman Bharat Pradhan Mantri Jan Arogya Yojana (PM-JAY)",
        ministry: "Ministry of Health and Family Welfare",
        description: "World's largest health insurance/assurance scheme fully financed by the government. Provides cover of Rs. 5 lakhs per family per year for secondary and tertiary care hospitalization.",
        category: "Health",
        type: "Insurance",
        state: "Central",
        benefits: "Cashless access to health care, coverage of ₹5 Lakhs per family per year.",
        eligibility: "Poor and vulnerable families listed in SECC 2011 database.",
        documentsRequired: ["Ayushman Card", "Aadhar Card", "Ration Card"],
        amount: 500000,
        gender: "All",
        ageMin: null,
        ageMax: null,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://pmjay.gov.in/",
        tags: ["health", "insurance", "hospitalization", "cashless"]
    },
    {
        title: "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
        ministry: "Ministry of Finance",
        description: "Accident insurance scheme offering accidental death and disability cover.",
        category: "Health",
        type: "Insurance",
        state: "Central",
        benefits: "₹2 Lakhs for accidental death/full disability, ₹1 Lakh for partial disability. Premium just ₹20/year.",
        eligibility: "All savings bank account holders aged 18 to 70 years.",
        documentsRequired: ["Bank Account", "Aadhar Card"],
        amount: 200000,
        gender: "All",
        ageMin: 18,
        ageMax: 70,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: new Date("2025-05-31"),
        status: "active",
        applicationUrl: "https://financialservices.gov.in/beta/en/pmsby",
        tags: ["accident", "insurance", "low cost"]
    },
    {
        title: "Pradhan Mantri Matru Vandana Yojana (PMMVY)",
        ministry: "Ministry of Women and Child Development",
        description: "Maternity benefit program implemented in all districts of the country in accordance with the provision of the National Food Security Act, 2013.",
        category: "Health",
        type: "Financial Assistance",
        state: "Central",
        benefits: "Cash incentive of ₹5,000 in three installments directly to bank account.",
        eligibility: "Pregnant women and lactating mothers (for first living child).",
        documentsRequired: ["MCP Card", "Aadhar Card", "Bank Passbook"],
        amount: 5000,
        gender: "Female",
        ageMin: 19,
        ageMax: 50,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://wcd.nic.in/schemes/pradhan-mantri-matru-vandana-yojana",
        tags: ["maternity", "women", "mother"]
    },
    {
        title: "Janani Suraksha Yojana (JSY)",
        ministry: "Ministry of Health and Family Welfare",
        description: "Safe motherhood intervention under the National Rural Health Mission (NRHM).",
        category: "Health",
        type: "Financial Assistance",
        state: "Central",
        benefits: "Cash assistance for institutional delivery. ₹1400 in rural areas and ₹1000 in urban areas for BPL/SC/ST women.",
        eligibility: "Pregnant women from BPL families, Sc and ST women.",
        documentsRequired: ["BPL Card", "SC/ST Certificate", "Hospital Discharge Card"],
        amount: 1400,
        gender: "Female",
        ageMin: 19,
        ageMax: 50,
        incomeLimit: 50000,
        caste: ["SC", "ST", "General", "OBC"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://nhm.gov.in/index1.php?lang=1&level=2&sublinkid=841&lid=309",
        tags: ["delivery", "maternity", "health"]
    },
    {
        title: "Rashtriya Swasthya Bima Yojana (RSBY)",
        ministry: "Ministry of Health and Family Welfare",
        description: "Health insurance for Below Poverty Line (BPL) families to provide protection against financial liabilities arising out of hospitalization.",
        category: "Health",
        type: "Insurance",
        state: "Central",
        benefits: "Hospitalization coverage up to ₹30,000 per family per annum.",
        eligibility: "BPL families, Unorganized sector workers.",
        documentsRequired: ["BPL Card", "Ration Card"],
        amount: 30000,
        gender: "All",
        ageMin: null,
        ageMax: null,
        incomeLimit: 50000,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "http://www.rsby.gov.in/",
        tags: ["bpl", "insurance", "health"]
    },
    {
        title: "Mission Indradhanush",
        ministry: "Ministry of Health and Family Welfare",
        description: "To ensure full immunization with all available vaccines for children up to two years of age and pregnant women.",
        category: "Health",
        type: "Service",
        state: "Central",
        benefits: "Free vaccination against 12 vaccine-preventable diseases.",
        eligibility: "Children up to 2 years and pregnant women.",
        documentsRequired: ["MCP Card"],
        amount: null,
        gender: "All",
        ageMin: 0,
        ageMax: 2,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://www.nhp.gov.in/mission-indradhanush1_pg",
        tags: ["vaccination", "children", "immunization"]
    },
    {
        title: "Central Government Health Scheme (CGHS)",
        ministry: "Ministry of Health and Family Welfare",
        description: "Comprehensive health care facilities for Central Government employees and pensioners.",
        category: "Health",
        type: "Insurance",
        state: "Central",
        benefits: "Outpatient and inpatient care, medicines, specialist consultation.",
        eligibility: "Central Govt employees, Pensioners, MPs, etc.",
        documentsRequired: ["Service ID", "CGHS Card"],
        amount: null,
        gender: "All",
        ageMin: null,
        ageMax: null,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://cghs.gov.in/",
        tags: ["government employees", "health", "pensioners"]
    },
     {
        title: "Ujjwala Sanitary Napkin Initiative",
        ministry: "OMC / State Govts",
        description: "To promote menstrual hygiene among women in rural areas.",
        category: "Health",
        type: "Subsidy",
        state: "Odisha",
        benefits: "Sanitary napkins at subsidized rates.",
        eligibility: "Women and adolescent girls in rural areas.",
        documentsRequired: ["Aadhar Card"],
        amount: null,
        gender: "Female",
        ageMin: 12,
        ageMax: 45,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Rural",
        deadline: null,
        status: "active",
        applicationUrl: "https://wcd.odisha.gov.in/",
        tags: ["hygiene", "women", "health"]
    },
    {
        title: "Mahatma Jyotiba Phule Jan Arogya Yojana (MJPJAY)",
        ministry: "Government of Maharashtra",
        description: "Flagship health insurance scheme of Government of Maharashtra.",
        category: "Health",
        type: "Insurance",
        state: "Maharashtra",
        benefits: "Cashless medical access up to ₹1.5 Lakhs per family per year for serious illnesses.",
        eligibility: "Orange and Yellow Ration Card holders in Maharashtra.",
        documentsRequired: ["Ration Card", "Aadhar Card"],
        amount: 150000,
        gender: "All",
        ageMin: null,
        ageMax: null,
        incomeLimit: 100000,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://www.jeevandayee.gov.in/",
        tags: ["maharashtra", "insurance", "critical care"]
    },
    {
        title: "Swasthya Sathi Scheme",
        ministry: "Government of West Bengal",
        description: "Basic health cover for secondary and tertiary care up to Rs 5 lakh per annum per family.",
        category: "Health",
        type: "Insurance",
        state: "West Bengal",
        benefits: "Cashless treatment up to ₹5 Lakhs, card issued in name of female head of family.",
        eligibility: "All residents of West Bengal.",
        documentsRequired: ["Swasthya Sathi Card", "Aadhar Card"],
        amount: 500000,
        gender: "All",
        ageMin: null,
        ageMax: null,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://swasthyasathi.gov.in/",
        tags: ["west bengal", "insurance", "universal health"]
    },
    {
        title: "Karunya Health Scheme",
        ministry: "Government of Kerala",
        description: "Critical illness coverage scheme funded by Kerala State Lotteries.",
        category: "Health",
        type: "Financial Assistance",
        state: "Kerala",
        benefits: "Financial assistance for treatment of cancer, heart disease, kidney diseases etc.",
        eligibility: "BPL families and low income households in Kerala.",
        documentsRequired: ["Income Certificate", "Medical Records", "Ration Card"],
        amount: 200000, // Varies
        gender: "All",
        ageMin: null,
        ageMax: null,
        incomeLimit: 300000,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "http://karunya.kerala.gov.in/",
        tags: ["kerala", "critical illness", "lottery funded"]
    },
    {
        title: "Chief Minister's Comprehensive Health Insurance Scheme (Amma)",
        ministry: "Government of Tamil Nadu",
        description: "Provide high quality treatment to the eligible population through government and private hospitals.",
        category: "Health",
        type: "Insurance",
        state: "Tamil Nadu",
        benefits: "Coverage up to ₹5 Lakhs per family per year.",
        eligibility: "Residents of TN with annual family income less than ₹72,000.",
        documentsRequired: ["Income Certificate", "Ration Card", "Aadhar Card"],
        amount: 500000,
        gender: "All",
        ageMin: null,
        ageMax: null,
        incomeLimit: 72000,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://www.cmchistn.com/",
        tags: ["tamil nadu", "insurance", "free treatment"]
    },
    {
        title: "Biju Swasthya Kalyan Yojana (BSKY)",
        ministry: "Government of Odisha",
        description: "Universal health coverage scheme working in cashless mode.",
        category: "Health",
        type: "Insurance",
        state: "Odisha",
        benefits: "Cashless treatment up to ₹5 Lakhs per family (₹10 Lakhs for women members).",
        eligibility: "All families covered under NFSA/SFSA and BSKY smart card holders.",
        documentsRequired: ["BSKY Card", "Ration Card"],
        amount: 500000,
        gender: "All",
        ageMin: null,
        ageMax: null,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://health.odisha.gov.in/bsky",
        tags: ["odisha", "women health", "insurance"]
    },
    {
        title: "Aarogyasri Scheme",
        ministry: "Government of Telangana",
        description: "Community health insurance scheme to provide financial protection to families living below poverty line.",
        category: "Health",
        type: "Insurance",
        state: "Telangana",
        benefits: "Coverage for serious ailments requiring hospitalization.",
        eligibility: "BPL families with White Ration Card.",
        documentsRequired: ["White Ration Card", "Aadhar Card"],
        amount: 200000,
        gender: "All",
        ageMin: null,
        ageMax: null,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://aarogyasri.telangana.gov.in/",
        tags: ["telangana", "insurance", "bpl"]
    },
     {
        title: "Atal Amrit Abhiyan",
        ministry: "Government of Assam",
        description: "Health assurance scheme covering critical care.",
        category: "Health",
        type: "Insurance",
        state: "Assam",
        benefits: "Cashless treatment up to ₹2 Lakhs per individual.",
        eligibility: "Individuals from APL and BPL families with income less than ₹5 Lakhs.",
        documentsRequired: ["Income Certificate", "Ration Card", "Aadhar Card"],
        amount: 200000,
        gender: "All",
        ageMin: null,
        ageMax: null,
        incomeLimit: 500000,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://atalamritabhiyan.assam.gov.in/",
        tags: ["assam", "insurance", "critical illness"]
    },
    {
        title: "Mukhyamantri Amrutam (MA) Yojana",
        ministry: "Government of Gujarat",
        description: "Tertiary care coverage for BPL families.",
        category: "Health",
        type: "Insurance",
        state: "Gujarat",
        benefits: "Cashless medical treatment up to ₹5 Lakhs per family.",
        eligibility: "BPL families and low income families.",
        documentsRequired: ["Income Certificate", "MA Card"],
        amount: 500000,
        gender: "All",
        ageMin: null,
        ageMax: null,
        incomeLimit: 400000,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://magujarat.com/",
        tags: ["gujarat", "insurance", "card"]
    },
    {
        title: "National Tuberculosis Elimination Program",
        ministry: "Ministry of Health and Family Welfare",
        description: "Program to eliminate TB from India.",
        category: "Health",
        type: "Service",
        state: "Central",
        benefits: "Free diagnosis and treatment. ₹500/month nutritional support (Nikshay Poshan Yojana).",
        eligibility: "All TB patients notified in Nikshay portal.",
        documentsRequired: ["Medical Diagnosis", "Bank Account for DBT"],
        amount: 500, // Monthly
        gender: "All",
        ageMin: null,
        ageMax: null,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://tbcindia.gov.in/",
        tags: ["tb", "nutrition", "health"]
    },
    {
        title: "Universal Health Insurance Scheme (UHIS)",
        ministry: "Public Sector Insurance Companies",
        description: "To provide health insurance cover to BPL families.",
        category: "Health",
        type: "Insurance",
        state: "Central",
        benefits: "Reimbursement of medical expenses up to ₹30,000.",
        eligibility: "BPL families.",
        documentsRequired: ["BPL Certificate"],
        amount: 30000,
        gender: "All",
        ageMin: null,
        ageMax: null,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://financialservices.gov.in/",
        tags: ["bpl", "reimbursement", "health"]
    },
    {
        title: "Dr. Muthulakshmi Reddy Maternity Benefit Scheme",
        ministry: "Government of Tamil Nadu",
        description: "To provide financial assistance to poor pregnant women.",
        category: "Health",
        type: "Financial Assistance",
        state: "Tamil Nadu",
        benefits: "Total assistance of ₹18,000.",
        eligibility: "Poor pregnant women aged 19+.",
        documentsRequired: ["Ration Card", "Bank Account", "Medical Certificate"],
        amount: 18000,
        gender: "Female",
        ageMin: 19,
        ageMax: 45,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://picme.tn.gov.in/",
        tags: ["maternity", "tamil nadu", "women"]
    },
    {
        title: "Himcare Scheme",
        ministry: "Government of Himachal Pradesh",
        description: "Cashless treatment scheme for those not covered under Ayushman Bharat.",
        category: "Health",
        type: "Insurance",
        state: "Himachal Pradesh",
        benefits: "Cashless treatment up to ₹5 Lakhs per year.",
        eligibility: "Residents of HP not covered under PM-JAY/Govt Employee Medical Reimbursement.",
        documentsRequired: ["Ration Card", "Aadhar Card"],
        amount: 500000,
        gender: "All",
        ageMin: null,
        ageMax: null,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://www.hpsbys.in/",
        tags: ["himachal", "insurance", "cashless"]
    }
];

const businessPoorSchemes = [
    {
        title: "Pradhan Mantri Mudra Yojana (PMMY)",
        ministry: "Ministry of Finance",
        description: "To provide loans up to 10 lakh to the non-corporate, non-farm small/micro enterprises.",
        category: "Business",
        type: "Loan",
        state: "Central",
        benefits: "Loans in three categories: Shishu (up to ₹50k), Kishore (₹50k-₹5L), Tarun (₹5L-₹10L). No collateral required.",
        eligibility: "Any Indian Citizen who has a business plan for a non-farm income generating activity.",
        documentsRequired: ["Business Plan", "KYC Documents", "Proof of Address"],
        amount: 1000000,
        gender: "All",
        ageMin: 18,
        ageMax: 65,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://www.mudra.org.in/",
        tags: ["loan", "business", "sme", "startup"]
    },
    {
        title: "Stand Up India Scheme",
        ministry: "Ministry of Finance",
        description: "Facilitate bank loans between ₹10 lakh and ₹1 Crore to at least one SC/ST borrower and at least one woman borrower per bank branch.",
        category: "Business",
        type: "Loan",
        state: "Central",
        benefits: "Bank loan of ₹10 Lakhs to ₹1 Crore for setting up a greenfield enterprise.",
        eligibility: "SC/ST and/or Woman entrepreneurs above 18 years.",
        documentsRequired: ["Caste Certificate", "Project Report", "Pan Card"],
        amount: 10000000,
        gender: "Female", // And SC/ST Males, but primary focus often women
        ageMin: 18,
        ageMax: null,
        incomeLimit: null,
        caste: ["SC", "ST", "General", "OBC"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://www.standupmitra.in/",
        tags: ["women", "sc/st", "business", "crore loan"]
    },
    {
        title: "PM Street Vendor's AtmaNirbhar Nidhi (PM SVANidhi)",
        ministry: "Ministry of Housing and Urban Affairs",
        description: "Micro-credit facility for street vendors.",
        category: "Business",
        type: "Loan",
        state: "Central",
        benefits: "Collateral free working capital loan up to ₹10,000. Interest subsidy @7% on regular repayment.",
        eligibility: "Street vendors in urban areas.",
        documentsRequired: ["Vending Certificate", "Aadhar Card"],
        amount: 10000,
        gender: "All",
        ageMin: 18,
        ageMax: null,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Urban",
        deadline: new Date("2024-12-31"),
        status: "active",
        applicationUrl: "https://pmsvanidhi.mohua.gov.in/",
        tags: ["street vendor", "loan", "micro credit"]
    },
    {
        title: "Prime Minister's Employment Generation Programme (PMEGP)",
        ministry: "Ministry of MSME",
        description: "Credit linked subsidy programme for generation of employment opportunities.",
        category: "Business",
        type: "Subsidy",
        state: "Central",
        benefits: "Subsidy up to 35% of project cost in rural areas and 25% in urban areas.",
        eligibility: "Any individual above 18 years. Class VIII pass for projects above ₹10 Lakhs in manufacturing.",
        documentsRequired: ["Project Report", "Education Certificate", "Caste Certificate", "Aadhar"],
        amount: 2500000, // Max project cost supported roughly
        gender: "All",
        ageMin: 18,
        ageMax: null,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://www.kviconline.gov.in/pmegpeportal/pmegphome/index.jsp",
        tags: ["subsidy", "business", "manufacturing", "employment"]
    },
    {
        title: "Pradhan Mantri Awaas Yojana - Gramin (PMAY-G)",
        ministry: "Ministry of Rural Development",
        description: "To provide a pucca house with basic amenities to all houseless households.",
        category: "Housing",
        type: "Financial Assistance",
        state: "Central",
        benefits: "Financial assistance of ₹1.20 Lakh in plains and ₹1.30 Lakh in hilly areas for house construction.",
        eligibility: "Homeless families and families living in kutcha houses as per SECC 2011.",
        documentsRequired: ["Aadhar Card", "Job Card (MGNREGA)", "Bank Account"],
        amount: 120000,
        gender: "All",
        ageMin: 18,
        ageMax: null,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Rural",
        deadline: null,
        status: "active",
        applicationUrl: "https://pmayg.nic.in/",
        tags: ["housing", "poor", "rural", "home loan"]
    },
    {
        title: "Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)",
        ministry: "Ministry of Rural Development",
        description: "Legal guarantee for one hundred days of employment in every financial year to adult members of any rural household.",
        category: "Employment",
        type: "Employment",
        state: "Central",
        benefits: "Guaranteed 100 days wage employment. Wages vary by state (approx ₹200-300 per day).",
        eligibility: "Rural households willing to do unskilled manual work.",
        documentsRequired: ["Job Card application", "Aadhar Card"],
        amount: 30000, // Approx annual
        gender: "All",
        ageMin: 18,
        ageMax: null,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Rural",
        deadline: null,
        status: "active",
        applicationUrl: "https://nrega.nic.in/",
        tags: ["employment", "rural", "wage", "poor"]
    },
    {
        title: "Antyodaya Anna Yojana (AAY)",
        ministry: "Ministry of Consumer Affairs, Food and Public Distribution",
        description: "To provide highly subsidized food grains to the poorest of the poor families.",
        category: "Ration",
        type: "Subsidy",
        state: "Central",
        benefits: "35 kg of food grains per family per month at heavily subsidized rates (Wheat ₹2/kg, Rice ₹3/kg).",
        eligibility: "Poorest of the poor families from amongst BPL families.",
        documentsRequired: ["AAY Ration Card"],
        amount: null,
        gender: "All",
        ageMin: null,
        ageMax: null,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://nfsa.gov.in/",
        tags: ["food", "ration", "poor", "hunger"]
    },
    {
        title: "Pradhan Mantri Ujjwala Yojana (PMUY)",
        ministry: "Ministry of Petroleum and Natural Gas",
        description: "To provide LPG connections to women from Below Poverty Line (BPL) households.",
        category: "Energy",
        type: "Subsidy",
        state: "Central",
        benefits: "LPG Connection with financial support of ₹1600. Free first refill and stove.",
        eligibility: "Adult woman of a BPL family.",
        documentsRequired: ["BPL Certificate", "Aadhar Card", "Ration Card"],
        amount: 1600,
        gender: "Female",
        ageMin: 18,
        ageMax: null,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://www.pmuy.gov.in/",
        tags: ["lpg", "gas", "women", "poor"]
    },
    {
        title: "Deen Dayal Antyodaya Yojana (DAY-NRLM)",
        ministry: "Ministry of Rural Development",
        description: "To alleviate rural poverty by building sustainable community institutions of the poor.",
        category: "Livelihood",
        type: "Financial Assistance",
        state: "Central",
        benefits: "Revolving Fund of ₹10,000-15,000 to SHGs. Community Investment Fund.",
        eligibility: "Rural poor women organized into SHGs.",
        documentsRequired: ["SHG meeting records", "Bank Account"],
        amount: 15000,
        gender: "Female",
        ageMin: 18,
        ageMax: null,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Rural",
        deadline: null,
        status: "active",
        applicationUrl: "https://aajeevika.gov.in/",
        tags: ["shg", "women", "livelihood", "rural"]
    },
    {
        title: "Atal Pension Yojana (APY)",
        ministry: "PFRDA",
        description: "A pension scheme for citizens of India, focused on the unorganized sector workers.",
        category: "Pension",
        type: "Pension",
        state: "Central",
        benefits: "Guaranteed minimum pension of ₹1000/₹2000/₹3000/₹4000/₹5000 per month at age 60.",
        eligibility: "Any citizen of India between 18-40 years.",
        documentsRequired: ["Savings Bank Account", "Aadhar Card"],
        amount: 5000, // Monthly pension value
        gender: "All",
        ageMin: 18,
        ageMax: 40,
        incomeLimit: null,
        caste: ["General", "OBC", "SC", "ST"],
        residence: "Both",
        deadline: null,
        status: "active",
        applicationUrl: "https://www.npscra.nsdl.co.in/scheme-details.php",
        tags: ["pension", "old age", "security", "unorganized"]
    }
];

async function seed() {
    console.log("🌱 Seeding Healthcare & Business schemes...");
    
    try {
        const users = await db.query.users.findMany({ limit: 1 });
        let adminId = null;
        
        if (users.length > 0) {
            adminId = users[0].id;
        }

        const allSchemes = [...healthcareSchemes, ...businessPoorSchemes].map(s => ({
            ...s,
            createdBy: adminId,
            applicationsCount: 0
        }));

        const result = await db.insert(schemes).values(allSchemes as any).returning();
        console.log(`✅ Successfully inserted ${result.length} schemes (20 Health, 10 Business/Poor)!`);
    } catch (error) {
        console.error("Error seeding schemes:", error);
    }
    
    process.exit(0);
}

seed();
